pipeline{
     agent any
     stages{
        stage("Compile stage"){
          steps{
             withMaven(maven: 'Maven'){
                 bat "mvn -f maven-project/pom.xml clean compile"
             }
          }
       }
       stage("Testing stage"){
        steps{
             withMaven(maven: 'Maven'){
                 bat "mvn  -f maven-project/pom.xml test"
             }
          }
       }
       stage("Deploy stage"){
        steps{
             withMaven(maven: 'Maven'){
                 bat "mvn -f maven-project/pom.xml deploy"
             }
          }
        }
       
    }
 }                